// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJWN6r65DDk68Gyk31in-F-8wuef0L48',
    appId: '1:236896031669:web:587df0fd405d346ed7fffc',
    messagingSenderId: '236896031669',
    projectId: 'flutternova-af031',
    authDomain: 'flutternova-af031.firebaseapp.com',
    storageBucket: 'flutternova-af031.firebasestorage.app',
    measurementId: 'G-YT90YMLH6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7zMkdOORDr3l4p6xRfB_ZKkMWtKRtwM',
    appId: '1:236896031669:android:1f3d6f72ca89635ad7fffc',
    messagingSenderId: '236896031669',
    projectId: 'flutternova-af031',
    storageBucket: 'flutternova-af031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wuJ7rLkoTJZ7qFFWbivBRuxqUO6252Y',
    appId: '1:236896031669:ios:477ccdf08ab1d50fd7fffc',
    messagingSenderId: '236896031669',
    projectId: 'flutternova-af031',
    storageBucket: 'flutternova-af031.firebasestorage.app',
    iosBundleId: 'com.example.flutterNova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5wuJ7rLkoTJZ7qFFWbivBRuxqUO6252Y',
    appId: '1:236896031669:ios:477ccdf08ab1d50fd7fffc',
    messagingSenderId: '236896031669',
    projectId: 'flutternova-af031',
    storageBucket: 'flutternova-af031.firebasestorage.app',
    iosBundleId: 'com.example.flutterNova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABJWN6r65DDk68Gyk31in-F-8wuef0L48',
    appId: '1:236896031669:web:9f0a0913d9044e21d7fffc',
    messagingSenderId: '236896031669',
    projectId: 'flutternova-af031',
    authDomain: 'flutternova-af031.firebaseapp.com',
    storageBucket: 'flutternova-af031.firebasestorage.app',
    measurementId: 'G-NJXYNGZC6B',
  );
}
